---
- name: My Play
  hosts: 192.168.7.37
  become: true
  gather_facts: no
  remote_user: ansible
  tasks:
  - name: install packages
    yum:
     name:
      - mariadb
      - httpd
      - samba
     state: latest
...
